export const WORKSHOP_STAGE_STEP_KEYS_PSS_MAP = {
  "GENERAL_TOPIC": [
    "WHATS_WORKING_RESPONSES",
    "WHATS_WORKING_REVIEW",
    "PROBLEMS_REPONSES",
    "PROBLEMS_VOTE",
    "PROBLEMS_REVIEW_VOTES",
    "REFRAME_PROBLEM_RESPONSE",
    "REFRAME_PROBLEM_VOTE",
    "REFRAME_PROBLEM_REVIEW_VOTES",
    "OPPORTUNITY_QUESTION_RESPONSE",
    "SOLUTIONS_RESPONSES",
    "SOLUTIONS_IMPACT_EFFORT",
    "SOLUTIONS_VOTE",
    "SOLUTIONS_REVIEW_VOTES",
    "EXPERIMENTS_HYPOTHESIS",
    "EXPERIMENTS_OWNERS"
  ],
  "MANY_EXISTING_PROBLEMS": [
    "PROBLEMS_VOTE",
    "PROBLEMS_REVIEW_VOTES",
    "REFRAME_PROBLEM_RESPONSE",
    "REFRAME_PROBLEM_VOTE",
    "REFRAME_PROBLEM_REVIEW_VOTES",
    "OPPORTUNITY_QUESTION_RESPONSE",
    "SOLUTIONS_RESPONSES",
    "SOLUTIONS_IMPACT_EFFORT",
    "SOLUTIONS_VOTE",
    "SOLUTIONS_REVIEW_VOTES",
    "EXPERIMENTS_HYPOTHESIS",
    "EXPERIMENTS_OWNERS"
  ],
  "ONE_EXISTING_PROBLEM": [
    "REFRAME_PROBLEM_RESPONSE",
    "REFRAME_PROBLEM_VOTE",
    "REFRAME_PROBLEM_REVIEW_VOTES",
    "OPPORTUNITY_QUESTION_RESPONSE",
    "SOLUTIONS_RESPONSES",
    "SOLUTIONS_IMPACT_EFFORT",
    "SOLUTIONS_VOTE",
    "SOLUTIONS_REVIEW_VOTES",
    "EXPERIMENTS_HYPOTHESIS",
    "EXPERIMENTS_OWNERS"
  ],
  "MANY_EXISTING_SOLUTIONS": [
    "SOLUTIONS_VOTE",
    "SOLUTIONS_REVIEW_VOTES",
    "EXPERIMENTS_HYPOTHESIS",
    "EXPERIMENTS_OWNERS"
  ],
  "ONE_EXISTING_SOLUTION": [
    "EXPERIMENTS_HYPOTHESIS",
    "EXPERIMENTS_OWNERS"
  ]
}
