export const WORKSHOP_STAGE_KEYS_PSS_MAP = {
  "GENERAL_TOPIC": [
    "WHATS_WORKING",
    "PROBLEMS",
    "REFRAME_PROBLEM",
    "OPPORTUNITY_QUESTION",
    "SOLUTIONS",
    "EXPERIMENTS"
  ],
  "EXISTING_PROBLEMS": [
    "REFRAME_PROBLEM",
    "OPPORTUNITY_QUESTION",
    "SOLUTIONS",
    "EXPERIMENTS"
  ],
  "EXISTING_SOLUTIONS": [
    "EXPERIMENTS"
  ]
}
